# frozen_string_literal: true

source 'https://rubygems.org'

group :development do
  gem 'rubocop'
  gem 'solargraph'
end

group :development, :test do
  gem 'codewars_test', git: 'https://github.com/codewars/ruby-test-framework.git'
  gem 'rspec-core'
  gem 'rspec-expectations'
end
